name: UNLIMITED
on:
  push:
    branches:
      - main
jobs:
  push_to_registry:
    name: Idk
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Forking
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bencdr/code-server-deploy-container:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
